library/config/routes.rb
Rails.application.routes.draw do
  devise_for :users do
      get '/log_out', to: 'devise/sessions#destroy'
  end

  resources :users
  resources :books
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'books#index'
end

library/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

library/app/models/book.rb
class Book < ApplicationRecord
    audited

    validates :title, presence: true,
                      uniqueness: true
end

library/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

library/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

library/app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]

  skip_before_action :authenticate_user!, only: [:index]

  # GET /books or /books.json
  def index
    @books = Book.all
  end

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to book_url(@book), notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_url(@book), notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :category, :year)
    end
end

library/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name)
    end
end

library/app/helpers/application_helper.rb
module ApplicationHelper
end

library/app/helpers/books_helper.rb
module BooksHelper
end

library/app/helpers/user_helper.rb
module UserHelper
end

library/app/helpers/users_helper.rb
module UsersHelper
end

library/app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row mb-3">
    <div class="col-md-4">
      <%= form.label :title, 'Título' %>
    </div>
    <div class="col-md-8">
      <%= form.text_field :title, class: 'form-control'  %>
    </div>
  </div>

  <div class="row mb-3">
    <div class="col-md-4">
      <%= form.label :category, 'Categoría' %>
    </div>
    <div class="col-md-8">
      <%= form.text_field :category , class: 'form-control' %>
    </div>
  </div>

  <div class="row mb-3">
    <div class="col-md-4">
      <%= form.label :year, 'Año' %>
    </div>
    <div class="col-md-8">
      <%= form.number_field :year, class: 'form-control'  %>
    </div>
  </div>

  <div class="row mb-3">
    <div class="col-sm-2">
      <%= form.submit class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

library/app/views/books/edit.html.erb
<div class="card">
  <div class="card-header">
    <h2>Editando Libro</h2>
  </div>
  <div class="card-body">
    <%= render 'form', book: @book %>
  </div>
</div>

<%= link_to 'Mostrar', @book %> |
<%= link_to 'Atrás', books_path %>

library/app/views/books/index.html.erb
<% if notice %>
  <div class="alert alert-warning" role="alert">
    <p id="notice"><%= notice %></p>
  </div>
<% end %>

<div class="card">
  <div class="card-body">
    <h2 class="card-title">Lista de Libros</h2>
    <div class="card-text">
      <table class="table table-bordered table-hover">
        <thead>
          <tr>
            <th>Título</th>
            <th>Categoría</th>
            <th>Año</th>
            <th class="text-center">Acciones</th>
          </tr>
        </thead>

        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td><%= book.title %></td>
              <td><%= book.category %></td>
              <td><%= book.year %></td>
              <td class="text-center">
                  <%= link_to 'Mostrar', book %> | 
                  <%= link_to 'Editar', edit_book_path(book) %> | 
                  <%= link_to 'Eliminar', book, method: :delete, data: { confirm: '¿Está seguro de eliminar este libro?' } %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<br>

<% if user_signed_in? %>
  <%= link_to 'Agregar un nuevo Libro', new_book_path %>
<% end %>

library/app/views/books/new.html.erb
<div class="card">
  <div class="card-header">
    <h2>Registrar nuevo libro</h2>
  </div>
  <div class="card-body">
    <%= render 'form', book: @book %>
  </div>
</div>

<%= link_to 'Atrás', books_path %>

library/app/views/books/show.html.erb
<% if notice %>
  <div class="alert alert-warning" role="alert">
    <p id="notice"><%= notice %></p>
  </div>
<% end %>

<div class="card" style="width: 50%;">
  <h2 class="card-title">Mostrando Libro</h2>
  <div class="card-body">
    <div class="row mb-3">
      <div class="col-md-4">
        <strong>Título:</strong>
      </div>
      <div class="col-md-8">
        <%= @book.title %>
      </div>
    </div>
    <div class="row mb-3">
      <div class="col-md-4">
        <strong>Categoría:</strong>
      </div>
      <div class="col-md-8">
        <%= @book.category %>
      </div>
    </div>
    <div class="row mb-3">
      <div class="col-md-4">
        <strong>Año:</strong>
      </div>
      <div class="col-md-8">
        <%= @book.year %>
      </div>
    </div>
  </div>
</div>

<%= link_to 'Editar', edit_book_path(@book) %> |
<%= link_to 'Atrás', books_path %>

library/app/views/shared/_header.html.erb
<head>
    <title>Libreria</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

library/app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container-fluid">
        <a class="navbar-brand" href="/"><h4>Librería</h4></a>
        <% if user_signed_in? %>
            <ul class="navbar-nav flex-row">
                <li class="nav-item me-3 me-lg-1">
                    <a class="nav-link d-sm-flex align-items-sm-center text-warning" href="#">
                        <strong class="d-none d-sm-block ms-1"><%= current_user.email %></strong>
                    </a>
                </li>
                <li class="nav-item me-3 me-lg-1">
                    <a class="nav-link d-sm-flex align-items-sm-center text-warning" data-confirm="¿Está seguro de cerrar la sesión?" data-method="delete" href="/users/sign_out">
                        <strong class="d-none d-sm-block ms-1">Cerrar sesión</strong>
                    </a>
                </li>
            </ul>
        <% else %>
            <ul class="navbar-nav flex-row">
                <li class="nav-item me-3 me-lg-1">
                    <a class="nav-link d-sm-flex align-items-sm-center text-warning" href="<%= new_user_session_path %>">
                        <strong class="d-none d-sm-block ms-1">Iniciar Sesión</strong>
                    </a>
                </li>
            </ul>
        <% end %>
    </div>
</nav>

library/app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

library/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

library/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

library/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

library/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>